services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:4200"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 120s 